[build]
  publish = "github.com/lpgarcia18/cienciadedadosesaude/public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.50"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
